http: define CURL_AT_LEAST_VERSION if it's not defined
I get this error:

    lib/http.c: In function ‘http_new’:
    lib/http.c:49:26: error: missing binary operator before token "("
    make: *** [all] Error 2

I'm using curl 7.22.0 from Ubuntu Precise, this:
https://github.com/gridcoin/Gridcoin-Research/blob/master/src/curlver.h

Current curlver.h:
https://github.com/curl/curl/blob/master/include/curl/curlver.h

The CURL_AT_LEAST_VERSION macro is fairly recent (was added in May 2015) ..
https://github.com/curl/curl/commit/39b9bf60d13ff7cb62a6a031c210d27a32113c4f